import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    // Define a estrutura HTML da página com o idioma definido como "en" (inglês)
    <html lang="en">
      <body>
        {/* O contêiner principal que envolve todo o conteúdo da página */}
        <div className="container">
          
          {/* Seção de cabeçalho da página */}
          <header className="header"><Header></Header></header>
          
          {/* Seção principal da página, onde o conteúdo dinâmico será renderizado.
              O conteúdo da página será passado via 'children'. */}
          <main className="body">{children}</main>
          
          {/* Seção de rodapé da página */}
          <footer className="footer"><Footer></Footer></footer>
        </div>
      </body>
    </html>
  );
}